

export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_AGENCIES_START = 'GET_AGENCIES_START';
export const GET_AGENCIES_SUCCESS = 'GET_AGENCIES_SUCCESS';
export const GET_AGENCIES_FAILURE = 'GET_AGENCIES_FAILURE';

export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';



export const CREATE_HUMAN_RESOURCES_START = 'CREATE_HUMAN_RESOURCES_START';
export const CREATE_HUMAN_RESOURCES_SUCCESS = 'CREATE_HUMAN_RESOURCES_SUCCESS';
export const CREATE_HUMAN_RESOURCES_FAILURE = 'CREATE_HUMAN_RESOURCES_FAILURE';

