

export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_AGENCIES_START = 'GET_AGENCIES_START';
export const GET_AGENCIES_SUCCESS = 'GET_AGENCIES_SUCCESS';
export const GET_AGENCIES_FAILURE = 'GET_AGENCIES_FAILURE';

export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';

export const GET_HUMAN_RESOURCES_START = "GET_HUMAN_RESOURCES_START";
export const GET_HUMAN_RESOURCES_SUCCESS = "GET_HUMAN_RESOURCES_SUCCESS";
export const GET_HUMAN_RESOURCES_FAILURE = "GET_HUMAN_RESOURCES_FAILURE";

export const OPEN_HUMAN_RESOURCES_FORM = "OPEN_HUMAN_RESOURCES_FORM";
export const CLOSE_HUMAN_RESOURCES_FORM = "CLOSE_HUMAN_RESOURCES_FORM";

export const CREATE_HUMAN_RESOURCES_START = 'CREATE_HUMAN_RESOURCES_START';
export const CREATE_HUMAN_RESOURCES_SUCCESS = 'CREATE_HUMAN_RESOURCES_SUCCESS';
export const CREATE_HUMAN_RESOURCES_FAILURE = 'CREATE_HUMAN_RESOURCES_FAILURE';

export const UPDATE_HUMAN_RESOURCES_START = 'UPDATE_HUMAN_RESOURCES_START';
export const UPDATE_HUMAN_RESOURCES_SUCCESS = 'UPDATE_HUMAN_RESOURCES_SUCCESS';
export const UPDATE_HUMAN_RESOURCES_FAILURE = 'UPDATE_HUMAN_RESOURCES_FAILURE';

export const DELETE_HUMAN_RESOURCES_START = 'DELETE_HUMAN_RESOURCES_START';
export const DELETE_HUMAN_RESOURCES_SUCCESS = 'DELETE_HUMAN_RESOURCES_SUCCESS';
export const DELETE_HUMAN_RESOURCES_FAILURE = 'DELETE_HUMAN_RESOURCES_FAILURE';

// select vendor
export const SELECT_HUMAN_RESOURCE = 'SELECT_HUMAN_RESOURCE';