
// Getting project
export const GET_PROJECT_START = "MAP:GET_PROJECT_START";
export const GET_PROJECT_SUCCESS = "MAP:GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "MAP:GET_PROJECT_FAILURE";
export const CLEAR_PROJECT = "MAP:CLEAR_PROJECT";
