
export const GET_HUMAN_RESOURCES_START = "GET_HUMAN_RESOURCES_START";
export const GET_HUMAN_RESOURCES_SUCCESS = "GET_HUMAN_RESOURCES_SUCCESS";
export const GET_HUMAN_RESOURCES_FAILURE = "GET_HUMAN_RESOURCES_FAILURE";

export const OPEN_HUMAN_RESOURCES_FORM = "OPEN_HUMAN_RESOURCES_FORM";
export const CLOSE_HUMAN_RESOURCES_FORM = "CLOSE_HUMAN_RESOURCES_FORM";