
// Getting sub project
export const GET_SUB_PROJECT_START = "MAP:GET_SUB_PROJECT_START";
export const GET_SUB_PROJECT_SUCCESS = "MAP:GET_SUB_PROJECT_SUCCESS";
export const GET_SUB_PROJECT_FAILURE = "MAP:GET_SUB_PROJECT_FAILURE";
export const CLEAR_SUB_PROJECT = "MAP:CLEAR_SUB_PROJECT";

export const GET_SUB_PROJECT_STATISTICS_START = "MAP:GET_SUB_PROJECT_STATISTICS_START";
export const GET_SUB_PROJECT_STATISTICS_SUCCESS = "MAP:GET_SUB_PROJECT_STATISTICS_SUCCESS";
export const GET_SUB_PROJECT_STATISTICS_FAILURE = "MAP:GET_SUB_PROJECT_STATISTICS_FAILURE";
export const CLEAR_SUB_PROJECTS_STATISTICS = "CLEAR_SUB_PROJECTS_STATISTICS";

export const SHOW_NATIONAL_SUB_PROJECTS_OVERVIEW = 'SIDE_NAV_MENU:SHOW_NATIONAL_SUB_PROJECTS_OVERVIEW';
export const SHOW_SUB_PROJECTS_OVERVIEW = 'SIDE_NAV_MENU:SHOW_SUB_PROJECTS_OVERVIEW';
