
// Getting sub project
export const GET_SUB_PROJECT_START = "MAP:GET_SUB_PROJECT_START";
export const GET_SUB_PROJECT_SUCCESS = "MAP:GET_SUB_PROJECT_SUCCESS";
export const GET_SUB_PROJECT_FAILURE = "MAP:GET_SUB_PROJECT_FAILURE";
export const CLEAR_SUB_PROJECT = "MAP:CLEAR_SUB_PROJECT";
