import {
  getProjectsStart,
  getProjectsSuccess,
  getProjectsFailure,
  getProjectStart,
  getProjectSuccess,
  getProjectFailure,
  createProjectStart,
  createProjectSuccess,
  createProjectFailure,
  updateProjectStart,
  updateProjectSuccess,
  updateProjectFailure,
  deleteProjectStart,
  deleteProjectSuccess,
  deleteProjectFailure,
  getSubProjectsStart,
  getSubProjectsSuccess,
  getSubProjectsFailure,
  createSubProjectStart,
  createSubProjectSuccess,
  createSubProjectFailure,
  updateSubProjectStart,
  updateSubProjectSuccess,
  updateSubProjectFailure,
  deleteSubProjectStart,
  deleteSubProjectSuccess,
  deleteSubProjectFailure,
  selectSubProject,
  openSubProjectForm,
  closeSubProjectForm,
  closeProjectForm,
  openProjectForm
} from './actions';

export const opensProjectForm = openProjectForm;
export const closesProjectForm = closeProjectForm;

export {
  getProjectsStart,
  getProjectsSuccess,
  getProjectsFailure,
  getProjectStart,
  getProjectSuccess,
  getProjectFailure,
  createProjectStart,
  createProjectSuccess,
  createProjectFailure,
  updateProjectStart,
  updateProjectSuccess,
  updateProjectFailure,
  deleteProjectStart,
  deleteProjectSuccess,
  deleteProjectFailure,
  getSubProjectsStart,
  getSubProjectsSuccess,
  getSubProjectsFailure,
  createSubProjectStart,
  createSubProjectSuccess,
  createSubProjectFailure,
  updateSubProjectStart,
  updateSubProjectSuccess,
  updateSubProjectFailure,
  deleteSubProjectStart,
  deleteSubProjectSuccess,
  deleteSubProjectFailure,
  selectSubProject,
  openSubProjectForm,
  closeSubProjectForm,
};