
// Retrieve Projects
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

// Retrieve single Project
export const GET_PROJECT_START = "GET_PROJECT_START";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
export const CLEAR_PROJECT = "CLEAR_PROJECT";

// Create Project
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

// Update exiting Project
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

// Delete exiting Project
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const OPEN_FORM = "OPEN_FORM";
export const CLOSE_FORM = "CLOSE_FORM";


// Retrieve agencies
export const GET_AGENCIES_START = 'GET_AGENCIES_START';
export const GET_AGENCIES_SUCCESS = 'GET_AGENCIES_SUCCESS';
export const GET_AGENCIES_FAILURE = 'GET_AGENCIES_FAILURE';

// Retrieve regions
export const GET_REGIONS_START = 'GET_REGIONS_START';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

// Retrieve districts
export const GET_DISTRICTS_START = 'GET_DISTRICTS_START';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';
export const GET_DISTRICTS_FAILURE = 'GET_DISTRICTS_FAILURE';

// Retrieve locations
export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';

// select vendor
export const SELECT_PROJECT = 'SELECT_PROJECT';

// Types for SUB_PROJECT
export const GET_SUB_PROJECTS_START = "GET_SUB_PROJECTS_START";
export const GET_SUB_PROJECTS_SUCCESS = "GET_SUB_PROJECTS_SUCCESS";
export const GET_SUB_PROJECTS_FAILURE = "GET_SUB_PROJECTS_FAILURE";

// Retrieve single Project
export const GET_SUB_PROJECT_START = "GET_SUB_PROJECT_START";
export const GET_SUB_PROJECT_SUCCESS = "GET_SUB_PROJECT_SUCCESS";
export const GET_SUB_PROJECT_FAILURE = "GET_SUB_PROJECT_FAILURE";
export const CLEAR_SUB_PROJECT = "CLEAR_SUB_PROJECT";

// Retrieve single Project element
export const GET_SUB_PROJECT_ELEMENT_START = "GET_SUB_PROJECT_ELEMENT_START";
export const GET_SUB_PROJECT_ELEMENT_SUCCESS = "GET_SUB_PROJECT_ELEMENT_SUCCESS";
export const GET_SUB_PROJECT_ELEMENT_FAILURE = "GET_SUB_PROJECT_ELEMENT_FAILURE";
export const CLEAR_SUB_PROJECT_ELEMENT = "CLEAR_SUB_PROJECT_ELEMENT";

export const OPEN_SUB_PROJECTS_FORM = "OPEN_SUB_PROJECTS_FORM";
export const CLOSE_SUB_PROJECTS_FORM = "CLOSE_SUB_PROJECTS_FORM";

export const CREATE_SUB_PROJECT_START = 'CREATE_SUB_PROJECT_START';
export const CREATE_SUB_PROJECT_SUCCESS = 'CREATE_SUB_PROJECT_SUCCESS';
export const CREATE_SUB_PROJECT_FAILURE = 'CREATE_SUB_PROJECT_FAILURE';

export const UPDATE_SUB_PROJECT_START = 'UPDATE_SUB_PROJECT_START';
export const UPDATE_SUB_PROJECT_SUCCESS = 'UPDATE_SUB_PROJECT_SUCCESS';
export const UPDATE_SUB_PROJECT_FAILURE = 'UPDATE_SUB_PROJECT_FAILURE';

export const DELETE_SUB_PROJECT_START = 'DELETE_SUB_PROJECT_START';
export const DELETE_SUB_PROJECT_SUCCESS = 'DELETE_SUB_PROJECT_SUCCESS';
export const DELETE_SUB_PROJECT_FAILURE = 'DELETE_SUB_PROJECT_FAILURE';

// select vendor
export const SELECT_SUB_PROJECT = 'SELECT_SUB_PROJECT';
