// Retrieve Projects
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

// Retrieve single Project
export const GET_PROJECT_START = "GET_PROJECT_START";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

// Create Project
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

// Update exiting Project
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

// Delete exiting Project
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const OPEN_PROJECTS_FORM = "OPEN_PROJECTS_FORM";
export const CLOSE_PROJECTS_FORM = "CLOSE_PROJECTS_FORM";

// Retrieve Items
export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

// Retrieve agencies
export const GET_AGENCIES_START = 'GET_AGENCIES_START';
export const GET_AGENCIES_SUCCESS = 'GET_AGENCIES_SUCCESS';
export const GET_AGENCIES_FAILURE = 'GET_AGENCIES_FAILURE';

// Retrieve regions
export const GET_REGIONS_START = 'GET_REGIONS_START';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

// Retrieve districts
export const GET_DISTRICTS_START = 'GET_DISTRICTS_START';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';
export const GET_DISTRICTS_FAILURE = 'GET_DISTRICTS_FAILURE';


// select vendor
export const SELECT_PROJECT = 'SELECT_PROJECT';

// Types for initiative
export const GET_INITIATIVES_START = "GET_INITIATIVES_START";
export const GET_INITIATIVES_SUCCESS = "GET_INITIATIVES_SUCCESS";
export const GET_INITIATIVES_FAILURE = "GET_INITIATIVES_FAILURE";

export const OPEN_INITIATIVES_FORM = "OPEN_INITIATIVES_FORM";
export const CLOSE_INITIATIVES_FORM = "CLOSE_INITIATIVES_FORM";

export const CREATE_INITIATIVE_START = 'CREATE_INITIATIVES_START';
export const CREATE_INITIATIVE_SUCCESS = 'CREATE_INITIATIVES_SUCCESS';
export const CREATE_INITIATIVE_FAILURE = 'CREATE_INITIATIVES_FAILURE';

export const UPDATE_INITIATIVE_START = 'UPDATE_INITIATIVES_START';
export const UPDATE_INITIATIVE_SUCCESS = 'UPDATE_INITIATIVES_SUCCESS';
export const UPDATE_INITIATIVE_FAILURE = 'UPDATE_INITIATIVES_FAILURE';

export const DELETE_INITIATIVE_START = 'DELETE_INITIATIVES_START';
export const DELETE_INITIATIVE_SUCCESS = 'DELETE_INITIATIVES_SUCCESS';
export const DELETE_INITIATIVE_FAILURE = 'DELETE_INITIATIVES_FAILURE';

// select vendor
export const SELECT_INITIATIVE = 'SELECT_INITIATIVE';
