
export const SET_INITIATIVES_GEO_JSON = "SET_INITIATIVES_GEO_JSON";
export const SET_HUMAN_RESOURCES_GEO_JSON = "SET_HUMAN_RESOURCES_GEO_JSON";
export const SET_ACTIVE_MAP_SIDE_MENU_ITEM = "SET_ACTIVE_MAP_SIDE_MENU_ITEM";
