
export const SET_INITIATIVES_GEO_JSON = "SET_INITIATIVES_GEO_JSON";
export const SET_HUMAN_RESOURCES_GEO_JSON = "SET_HUMAN_RESOURCES_GEO_JSON";
export const SET_ACTIVE_MAP_SIDE_MENU_ITEM = "SET_ACTIVE_MAP_SIDE_MENU_ITEM";

export const SET_SHOW_FEATURE_DETAILS = "SET_SHOW_FEATURE_DETAILS";

export const SET_PROJECTS_SPATIAL_DATA = 'MAP:SET_PROJECTS_SPATIAL_DATA';



// getting projects overview per regions
export const GET_PROJECTS_OVERVIEW_START = "GET_PROJECTS_OVERVIEW_START";
export const GET_PROJECTS_OVERVIEW_SUCCESS = "GET_PROJECTS_OVERVIEW_SUCCESS";
export const GET_PROJECTS_OVERVIEW_FAILURE = "GET_PROJECTS_OVERVIEW_FAILURE";
export const CLEAR_PROJECTS_OVERVIEW = "CLEAR_PROJECTS_OVERVIEW";

// map loader
export const SHOW_MAP_LOADER = 'SHOW_MAP_LOADER';


// getting projects based on a region
export const GET_PROJECTS_BY_REGION_START = "GET_PROJECTS_BY_REGION_START";
export const GET_PROJECTS_BY_REGION_SUCCESS = "GET_PROJECTS_BY_REGION_SUCCESS";
export const GET_PROJECTS_BY_REGION_FAILURE = "GET_PROJECTS_BY_REGION_FAILURE";
export const CLEAR_REGION_PROJECTS = "CLEAR_REGION_PROJECTS";


// getting region details
export const GET_REGION_START = "GET_REGION_START";
export const GET_REGION_SUCCESS = "GET_REGION_SUCCESS";
export const GET_REGION_FAILURE = "GET_REGION_FAILURE";
export const CLEAR_REGION_DETAILS = "CLEAR_REGION_DETAILS";

export const GET_REGION_PROJECT_STATISTICS_START = "GET_REGION_PROJECT_STATISTICS_START";
export const GET_REGION_PROJECT_STATISTICS_SUCCESS = "GET_REGION_PROJECT_STATISTICS_SUCCESS";
export const GET_REGION_PROJECT_STATISTICS_FAILURE = "GET_REGION_PROJECT_STATISTICS_FAILURE";
export const CLEAR_REGION_PROJECTS_STATISTICS = "CLEAR_REGION_PROJECTS_STATISTICS";

export const GET_PROJECT_STATISTICS_START = "GET_PROJECT_STATISTICS_START";
export const GET_PROJECT_STATISTICS_SUCCESS = "GET_PROJECT_STATISTICS_SUCCESS";
export const GET_PROJECT_STATISTICS_FAILURE = "GET_PROJECT_STATISTICS_FAILURE";

export const GET_PROJECTS_STATISTICS_START = "GET_PROJECTS_STATISTICS_START";
export const GET_PROJECTS_STATISTICS_SUCCESS = "GET_PROJECTS_STATISTICS_SUCCESS";
export const GET_PROJECTS_STATISTICS_FAILURE = "GET_PROJECTS_STATISTICS_FAILURE";
export const CLEAR_PROJECTS_STATISTICS = "CLEAR_PROJECTS_STATISTICS";

// SIDE NAV MENU
export const SHOW_NATIONAL_PROJECTS_OVERVIEW = 'SIDE_NAV_MENU:SHOW_NATIONAL_PROJECTS_OVERVIEW';
export const SHOW_REGIONAL_PROJECTS_OVERVIEW = 'SIDE_NAV_MENU:SHOW_REGIONAL_PROJECTS_OVERVIEW';
