
export const SET_INITIATIVES_GEO_JSON = "SET_INITIATIVES_GEO_JSON";
export const SET_HUMAN_RESOURCES_GEO_JSON = "SET_HUMAN_RESOURCES_GEO_JSON";
export const SET_ACTIVE_MAP_SIDE_MENU_ITEM = "SET_ACTIVE_MAP_SIDE_MENU_ITEM";

export const SET_SHOW_FEATURE_DETAILS = "SET_SHOW_FEATURE_DETAILS";

export const SET_PROJECTS_SPATIAL_DATA = 'MAP:SET_PROJECTS_SPATIAL_DATA';



// getting projects overview per regions
export const GET_PROJECTS_OVERVIEW_START = "GET_PROJECTS_OVERVIEW_START";
export const GET_PROJECTS_OVERVIEW_SUCCESS = "GET_PROJECTS_OVERVIEW_SUCCESS";
export const GET_PROJECTS_OVERVIEW_FAILURE = "GET_PROJECTS_OVERVIEW_FAILURE";
export const CLEAR_PROJECTS_OVERVIEW = "CLEAR_PROJECTS_OVERVIEW";

// map loader
export const SHOW_MAP_LOADER = 'SHOW_MAP_LOADER';
