// Retrieve Tickets
export const GET_TICKETS_START = "GET_TICKETS_START";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_FAILURE = "GET_TICKETS_FAILURE";

export const GET_TICKET_START = "GET_TICKET_START";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";

export const CREATE_PROJECT_TICKET_START = "CREATE_PROJECT_TICKET_START";
export const CREATE_PROJECT_TICKET_SUCCESS = "CREATE_PROJECT_TICKET_SUCCESS";
export const CREATE_PROJECT_TICKET_FAILURE = "CREATE_PROJECT_TICKET_FAILURE";
