// Retrieve Tickets
export const GET_PROCURING_ENTITIES_START = "GET_PROCURING_ENTITIES_START";
export const GET_PROCURING_ENTITIES_SUCCESS = "GET_PROCURING_ENTITIES_SUCCESS";
export const GET_PROCURING_ENTITIES_FAILURE = "GET_PROCURING_ENTITIES_FAILURE";

export const GET_TICKET_START = "GET_TICKET_START";
export const GET_TICKET_SUCCESS = "GET_TICKET_SUCCESS";
export const GET_TICKET_FAILURE = "GET_TICKET_FAILURE";
