// Retrieve Items
export const GET_BORROWERS_START = 'GET_BORROWERS_START';
export const GET_BORROWERS_SUCCESS = 'GET_BORROWERS_SUCCESS';
export const GET_BORROWERS_FAILURE = 'GET_BORROWERS_FAILURE';

// Create Project BORROWERS
export const CREATE_PROJECT_SECTOR_START = 'CREATE_PROJECT_SECTOR_START';
export const CREATE_PROJECT_SECTOR_SUCCESS = 'CREATE_PROJECT_SECTOR_SUCCESS';
export const CREATE_PROJECT_SECTOR_FAILURE = 'CREATE_PROJECT_SECTOR_FAILURE';
