// Retrieve borrowers
export const GET_BORROWERS_START = 'GET_BORROWERS_START';
export const GET_BORROWERS_SUCCESS = 'GET_BORROWERS_SUCCESS';
export const GET_BORROWERS_FAILURE = 'GET_BORROWERS_FAILURE';

// Retrieve funding organinzation
export const GET_FUNDING_ORG_START = 'GET_FUNDING_ORG_START';
export const GET_FUNDING_ORG_SUCCESS = 'GET_FUNDING_ORG_SUCCESS';
export const GET_FUNDING_ORG_FAILURE = 'GET_FUNDING_ORG_FAILURE';
