
// Types for Focal people
export const GET_FOCAL_PEOPLE_START = "GET_FOCAL_PEOPLE_START";
export const GET_FOCAL_PEOPLE_SUCCESS = "GET_FOCAL_PEOPLE_SUCCESS";
export const GET_FOCAL_PEOPLE_FAILURE = "GET_FOCAL_PEOPLE_FAILURE";
