
// Retrieve Projects
export const GET_PROJECTS_START = "GET_PROJECTS_START";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

// Retrieve single Project
export const GET_PROJECT_START = "GET_PROJECT_START";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";
export const CLEAR_PROJECT = "CLEAR_PROJECT";

// Create Project
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

// Update exiting Project
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';

// Delete exiting Project
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const OPEN_FORM = "OPEN_FORM";
export const CLOSE_FORM = "CLOSE_FORM";

// Retrieve regions
export const GET_REGIONS_START = 'GET_REGIONS_START';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

// Retrieve districts
export const GET_DISTRICTS_START = 'GET_DISTRICTS_START';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';
export const GET_DISTRICTS_FAILURE = 'GET_DISTRICTS_FAILURE';

// Retrieve locations
export const GET_LOCATIONS_START = 'GET_LOCATIONS_START';
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS';
export const GET_LOCATIONS_FAILURE = 'GET_LOCATIONS_FAILURE';

// Retrieve environmental categories
export const GET_ENVIRONMENTAL_CATEGORIES_START = 'GET_ENVIRONMENTAL_CATEGORIES_START';
export const GET_ENVIRONMENTAL_CATEGORIES_SUCCESS = 'GET_ENVIRONMENTAL_CATEGORIES_SUCCESS';
export const GET_ENVIRONMENTAL_CATEGORIES_FAILURE = 'GET_ENVIRONMENTAL_CATEGORIES_FAILURE';

// select vendor
export const SELECT_PROJECT = 'SELECT_PROJECT';


// Types for Sub project form
export const OPEN_SUB_PROJECT_FORM = 'OPEN_SUB_PROJECT_FORM';
export const OPEN_SUB_PROJECT_SURVEY_FORM = 'OPEN_SUB_PROJECT_SURVEY_FORM';
export const CLOSE_SUB_PROJECT_FORM = 'CLOSE_SUB_PROJECT_FORM';
export const CLOSE_SUB_PROJECT_SURVEY_FORM = 'CLOSE_SUB_PROJECT_SURVEY_FORM';

// Retrieve single Project
export const GET_SUB_PROJECT_START = "GET_SUB_PROJECT_START";
export const GET_SUB_PROJECT_SUCCESS = "GET_SUB_PROJECT_SUCCESS";
export const GET_SUB_PROJECT_FAILURE = "GET_SUB_PROJECT_FAILURE";
export const CLEAR_SUB_PROJECT = "CLEAR_SUB_PROJECT";

// Retrieve single Project element
export const GET_SUB_PROJECT_ELEMENT_START = "GET_SUB_PROJECT_ELEMENT_START";
export const GET_SUB_PROJECT_ELEMENT_SUCCESS = "GET_SUB_PROJECT_ELEMENT_SUCCESS";
export const GET_SUB_PROJECT_ELEMENT_FAILURE = "GET_SUB_PROJECT_ELEMENT_FAILURE";
export const CLEAR_SUB_PROJECT_ELEMENT = "CLEAR_SUB_PROJECT_ELEMENT";


export const CREATE_SUB_PROJECT_START = 'CREATE_SUB_PROJECT_START';
export const CREATE_SUB_PROJECT_SUCCESS = 'CREATE_SUB_PROJECT_SUCCESS';
export const CREATE_SUB_PROJECT_FAILURE = 'CREATE_SUB_PROJECT_FAILURE';

export const UPDATE_SUB_PROJECT_START = 'UPDATE_SUB_PROJECT_START';
export const UPDATE_SUB_PROJECT_SUCCESS = 'UPDATE_SUB_PROJECT_SUCCESS';
export const UPDATE_SUB_PROJECT_FAILURE = 'UPDATE_SUB_PROJECT_FAILURE';

export const DELETE_SUB_PROJECT_START = 'DELETE_SUB_PROJECT_START';
export const DELETE_SUB_PROJECT_SUCCESS = 'DELETE_SUB_PROJECT_SUCCESS';
export const DELETE_SUB_PROJECT_FAILURE = 'DELETE_SUB_PROJECT_FAILURE';

// select vendor
export const SELECT_SUB_PROJECT = 'SELECT_SUB_PROJECT';

// Create Project sectors
export const CREATE_PROJECT_LOCATION_START = 'CREATE_PROJECT_LOCATION_START';
export const CREATE_PROJECT_LOCATION_SUCCESS = 'CREATE_PROJECT_LOCATION_SUCCESS';
export const CREATE_PROJECT_LOCATION_FAILURE = 'CREATE_PROJECT_LOCATION_FAILURE';

export const GET_ITEMS_START= 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_PROGRESS_START= 'GET_PROGRESS_START';
export const GET_PROGRESS_SUCCESS = 'GET_PROGRESS_SUCCESS';
export const GET_PROGRESS_FAILURE = 'GET_PROGRESS_FAILURE';

