
export const GET_SUB_PROJECT_ITEMS_START= 'GET_SUB_PROJECT_ITEMS_START';
export const GET_SUB_PROJECT_ITEMS_SUCCESS = 'GET_SUB_PROJECT_ITEMS_SUCCESS';
export const GET_SUB_PROJECT_ITEMS_FAILURE = 'GET_SUB_PROJECT_ITEMS_FAILURE';


export const GET_SUB_PROJECT_EQUIPMENTS_START= 'GET_SUB_PROJECT_EQUIPMENTS_START';
export const GET_SUB_PROJECT_EQUIPMENTS_SUCCESS = 'GET_SUB_PROJECT_EQUIPMENTS_SUCCESS';
export const GET_SUB_PROJECT_EQUIPMENTS_FAILURE = 'GET_SUB_PROJECT_EQUIPMENTS_FAILURE';

