
export const GET_SUB_PROJECT_ITEMS_START= 'GET_SUB_PROJECT_ITEMS_START';
export const GET_SUB_PROJECT_ITEMS_SUCCESS = 'GET_SUB_PROJECT_ITEMS_SUCCESS';
export const GET_SUB_PROJECT_ITEMS_FAILURE = 'GET_SUB_PROJECT_ITEMS_FAILURE';


export const GET_SUB_PROJECT_EQUIPMENTS_START= 'GET_SUB_PROJECT_EQUIPMENTS_START';
export const GET_SUB_PROJECT_EQUIPMENTS_SUCCESS = 'GET_SUB_PROJECT_EQUIPMENTS_SUCCESS';
export const GET_SUB_PROJECT_EQUIPMENTS_FAILURE = 'GET_SUB_PROJECT_EQUIPMENTS_FAILURE';

export const CREATE_SUB_PROJECT_ITEM_START = 'CREATE_SUB_PROJECT_ITEM_START';
export const CREATE_SUB_PROJECT_ITEM_SUCCESS = 'CREATE_SUB_PROJECT_ITEM_SUCCESS';
export const CREATE_SUB_PROJECT_ITEM_FAILURE = 'CREATE_SUB_PROJECT_ITEM_FAILURE';



